inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'db/migrate/*.hyrax.rb'
    - 'spec/internal_test_hyku/**/*'
    - 'vendor/**/*' 

Metrics/BlockLength:
  Exclude:
    - 'app/views/hyku/api/v1/**/*.jbuilder'
    - 'spec/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/requests/**/*'

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'hyku-api.gemspec'

Style/GuardClause:
  Exclude:
    - 'app/controllers/hyku/api/v1/tenant_controller.rb'
