inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'db/migrate/*.hyrax.rb'
    - 'spec/internal_test_hyku/**/*'
    - 'vendor/**/*' 

Metrics/BlockLength:
  Exclude:
    - 'app/views/hyku/api/v1/**/*.json.jbuilder'
    - 'config/routes.rb'
    - 'spec/**/*'
Metrics/LineLength:
  Exclude:
    - 'app/controllers/hyku/api/v1/reviews_controller.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/requests/**/*'

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'hyku-api.gemspec'
Style/GuardClause:
  Exclude:
    - 'app/controllers/hyku/api/v1/tenant_controller.rb'
Naming/AccessorMethodName:
  Exclude:
    - 'app/controllers/hyku/api/v1/sessions_controller.rb'
Style/BlockDelimiters:
  Exclude:
    - 'app/controllers/hyku/api/v1/reviews_controller.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/requests/v1/search_spec.rb'
